/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface EventsInterface extends ethers.utils.Interface {
  functions: {
    "createEvent(string,string)": FunctionFragment;
    "events(uint256)": FunctionFragment;
    "eventsMap(string)": FunctionFragment;
    "findEventById(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createEvent",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "events",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "eventsMap", values: [string]): string;
  encodeFunctionData(
    functionFragment: "findEventById",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eventsMap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "findEventById",
    data: BytesLike
  ): Result;

  events: {};
}

export class Events extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EventsInterface;

  functions: {
    createEvent(
      _id: string,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createEvent(string,string)"(
      _id: string,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    events(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    "events(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    eventsMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    "eventsMap(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    findEventById(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    "findEventById(string)"(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;
  };

  createEvent(
    _id: string,
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createEvent(string,string)"(
    _id: string,
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  events(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & { id: string; name: string; exists: boolean }
  >;

  "events(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & { id: string; name: string; exists: boolean }
  >;

  eventsMap(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & { id: string; name: string; exists: boolean }
  >;

  "eventsMap(string)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & { id: string; name: string; exists: boolean }
  >;

  findEventById(
    _eventId: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & { id: string; name: string; exists: boolean }
  >;

  "findEventById(string)"(
    _eventId: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & { id: string; name: string; exists: boolean }
  >;

  callStatic: {
    createEvent(
      _id: string,
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "createEvent(string,string)"(
      _id: string,
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    events(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    "events(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    eventsMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    "eventsMap(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    findEventById(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;

    "findEventById(string)"(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & { id: string; name: string; exists: boolean }
    >;
  };

  filters: {};

  estimateGas: {
    createEvent(
      _id: string,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createEvent(string,string)"(
      _id: string,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    events(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "events(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    eventsMap(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "eventsMap(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    findEventById(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "findEventById(string)"(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createEvent(
      _id: string,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createEvent(string,string)"(
      _id: string,
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    events(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "events(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    eventsMap(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "eventsMap(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    findEventById(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "findEventById(string)"(
      _eventId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
